inherits:
  - duplicated
  - utils:base
  - utils:fix
ignore-paths:
  - acceptance_tests/pyramid_ogcapi_test_app/ogcapi_features.py
  - acceptance_tests/gunicorn.conf.py

pylint:
  disable:
    - line-too-long # done by black
    - missing-timeout # done globally by c2cwsgiutils
    - too-many-arguments

pycodestyle:
  disable:
    - E722 # Do not use bare 'except'
    - E501 # Line too long

pydocstyle:
  disable:
    - D212 # Multi-line docstring summary should start at the first line
    - D202 # No blank lines allowed after function docstring
    - D200 # One-line docstring should fit on one line with quotes
    - D203 # 1 blank line required before class docstring

pyorama:
  run: true
mypy:
  options:
    python-version: '3.9'
ruff:
  options:
    target-version: py39
