---
strictness: veryhigh
max-line-length: 110
doc-warnings: true

ignore-paths:
  - acceptance_tests/pyramid_ogcapi_test_app/ogcapi_features.py
  - acceptance_tests/gunicorn.conf.py

pylint:
  disable:
    - wrong-import-order # done by isort
    - line-too-long # done by black
    - missing-timeout # done globally by c2cwsgiutils
    - too-many-arguments

pycodestyle:
  disable:
    - E203 # Whitespace before ':'
    - E722 # Do not use bare 'except'
    - E501 # Line too long

pydocstyle:
  disable:
    - D212 # Multi-line docstring summary should start at the first line
    - D202 # No blank lines allowed after function docstring
    - D200 # One-line docstring should fit on one line with quotes

mypy:
  run: true

mccabe:
  run: false

bandit:
  run: true
  options:
    config: .bandit.yaml

pyorama:
  run: true
