version: '2.2'

services:
  db:
    image: camptocamp/postgres:14-postgis-3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tests

  redis:
    image: redis:7.4
    user: www-data
    restart: unless-stopped

  application:
    image: camptocamp/application:latest
    ports:
      - '9123:8080'
    links:
      - db
    environment:
      - C2C_REDIS_URL=redis://redis:6379/0
      - SQLALCHEMY_URL=postgresql://postgres:postgres@db:5432/tests
    volumes:
      - ./results:/app/results
